---
    - name: install nginx
      yum:
        name: nginx
        state: installed
        update_cache: true

    - name: copy html page
      copy:
        src: "roles/nginx/files/{{ item }}"
        dest: /usr/share/nginx/html
      with_items:
        - tompencil.jpeg
        - index3.html

    - name: copy nginx.conf
      copy:
         src: roles/nginx/files/nginx.conf
         dest: /etc/nginx/nginx.conf 

    - name: enable and start nginx service
      systemd:
        name: nginx
        state: restarted 
        enabled: yes
...


