---
- name: install keepalived
  yum:
    name: keepalived
    state: installed
    update_cache: true

- name: configure keepalived.conf
  template:
     src: templates/keepalived.conf.j2
     dest: /etc/keepalived/keepalived.conf 

- name: enable and start keepalived service
  systemd:
    name: keepalived
    state: restarted 
    enabled: yes
...
